# Generated by Django 3.2.3 on 2023-06-24 21:52

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe_author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Минимальное время 1 мин.'), django.core.validators.MaxValueValidator(1440, 'Не многовато ли? Максимально 1440 мин. - это 24 часа.')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[users.validators.validate_username], verbose_name='Название'),
        ),
    ]
