# Generated by Django 3.2.3 on 2023-06-13 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230613_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeRecipe',
            new_name='Favorite',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='\nrecipes_likerecipe рецепт уже в избранных\n',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='\nrecipes_favorite рецепт уже в избранных\n'),
        ),
    ]
