# Generated by Django 3.2.3 on 2023-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230620_2255'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='\nrecipes_favorite рецепт уже в избранных\n',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='\nrecipes_shoppingcart рецепт уже в корзине\n',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_has_been_already_added_in_favorites'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_has_been_already_added_in_shoppingcart'),
        ),
    ]
