# Generated by Django 3.2.3 on 2023-06-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230621_0937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipe_has_been_already_added_in_favorites',
        ),
    ]
