# Generated by Django 3.2.3 on 2023-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230613_2212'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientquantity',
            name='\nrecipes_ingredientquantity ингридиент уже добавлен\n',
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='\nrecipes_ingredientquantity ингридиент уже добавлен\n'),
        ),
    ]
