# Generated by Django 3.2.3 on 2023-06-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230614_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='quantity',
            new_name='amount',
        ),
    ]
