# Generated by Django 3.2.3 on 2023-06-24 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='_users_user_follows_+', through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
