# Generated by Django 3.2.3 on 2023-06-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230607_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscription',
        ),
    ]
